### ISSUE TITLE
Protocol integration - Pods

### ISSUE THREAD

**Issue by sgzerbo** [karpatkey/defyes#201]
https://www.pods.finance/

**Comment by sgzerbo** [comment]
Wallet 0x58e6c7ab55aa9012eacca16d1ed4c15795669e1c has some funds in Pod protocol, so it can be used as a test case for analysis

**Comment by maurob** [comment]
Part of this issue is resolved by:
- https://github.com/karpatkey/defyes/pull/334
- https://github.com/karpatkey/defyes/pull/335
  - where https://github.com/karpatkey/defyes/pull/335/files/b5032f52dda3c72b7b0329d2b081d454f93ba7ee..fbd75c70ebe7713fc050c5b3ca49a5bda4c35858 shows de diff of 335 excluding the changes in 334.

**Comment by maurob** [comment]
This issue was completed solved since the https://github.com/karpatkey/defyes/pull/336 integration.
